<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="74190" started-at="2020-06-04T07:26:09Z" finished-at="2020-06-04T07:27:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="74190" started-at="2020-06-04T07:26:09Z" finished-at="2020-06-04T07:27:23Z">
      <class name="com.crm.qa.testcases.Fixed_deposit_Test">
        <test-method status="PASS" signature="setpmethod()[pri:0, instance:com.crm.qa.testcases.Fixed_deposit_Test@6b09bb57]" name="setpmethod" is-config="true" duration-ms="26064" started-at="2020-06-04T12:56:09Z" finished-at="2020-06-04T12:56:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setpmethod -->
        <test-method status="PASS" signature="exceldatadriven()[pri:0, instance:com.crm.qa.testcases.Fixed_deposit_Test@6b09bb57]" name="exceldatadriven" duration-ms="10271" started-at="2020-06-04T12:56:35Z" finished-at="2020-06-04T12:56:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exceldatadriven -->
        <test-method status="PASS" signature="readingformexcel()[pri:0, instance:com.crm.qa.testcases.Fixed_deposit_Test@6b09bb57]" name="readingformexcel" duration-ms="21804" started-at="2020-06-04T12:56:45Z" finished-at="2020-06-04T12:57:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readingformexcel -->
        <test-method status="PASS" signature="sample()[pri:0, instance:com.crm.qa.testcases.Fixed_deposit_Test@6b09bb57]" name="sample" duration-ms="11870" started-at="2020-06-04T12:57:07Z" finished-at="2020-06-04T12:57:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sample -->
        <test-method status="FAIL" signature="sample2()[pri:0, instance:com.crm.qa.testcases.Fixed_deposit_Test@6b09bb57]" name="sample2" duration-ms="4137" started-at="2020-06-04T12:57:19Z" finished-at="2020-06-04T12:57:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at com.crm.qa.testcases.Fixed_deposit_Test.sample2(Fixed_deposit_Test.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sample2 -->
      </class> <!-- com.crm.qa.testcases.Fixed_deposit_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
